language: nodejs
node_js:
  - 16

cache:
  yarn: true
  directories:
  - node_modules

env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH

before_deploy:
  - zip -r toyproject-01 *
  - mkdir -p deploy #상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv toyproject-01.zip deploy/toyproject-01.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: swlee-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - skek7811@gmail.com
