version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/front-end/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: rm-old.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: deploy.sh #엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링부트를 시작
      timeout: 120
      runas: ec2-user